GLIB_VERSION="2.4.13.6"
GLIB_ARCHIVE_FILE=$GLIB_NAME-$GLIB_VERSION.zip
GLIB_LINK_ROOT=https://github.com/opencv/opencv/archive
GLIB_LINK=$GLIB_LINK_ROOT/$GLIB_VERSION.zip
GLIB_LINK_DOWNLOAD="wget $GLIB_LINK -O $GLIB_ARCHIVE_FILE"
