GLIB_VERSION="1.2.15"
GLIB_VERSION_NAME="SDL"
GLIB_VERSION_FULL_NAME=$GLIB_VERSION_NAME-$GLIB_VERSION
GLIB_ARCHIVE_FILE=$GLIB_NAME-$GLIB_VERSION.zip
GLIB_LINK_ROOT=https://www.libsdl.org/release
GLIB_LINK=$GLIB_LINK_ROOT/$GLIB_VERSION_FULL_NAME.zip
GLIB_LINK_DOWNLOAD="wget $GLIB_LINK -O $GLIB_ARCHIVE_FILE"
